server:
  port: 29090         # 当前项目所在服务的端口号

# 配置日志级别为info
logging:
  level:
    root: info

# swagger增强
knife4j:
  enable: true
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '智能医生(DEEPSEEK-DOCTOR)服务'
      display-name: DEEPSEEK-DOCTOR
      paths-to-match: '/**'
      packages-to-scan: com.o0u0o.controller
