server:
  port: 29090         # 当前项目所在服务的端口号

# 配置日志级别为info
logging:
  level:
    root: info

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '统一接口(UNICOM-API)服务'
      paths-to-match: '/**'
      packages-to-scan: com.o0u0o.controller
knife4j:                      # swagger增强
  enable: true
  openapi:
    title: 统一接口(UNICOM-API)服务Swagger文档
    description: "`统一短信平台-统一接口(UNICOM-API)服务`,**接口文档**"
    email: jobs@techgeng.com
    concat: o0u0o
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/