spring:
  application:
    name: deepseek-doctor # 定义当前项目的应用名称
  profiles:
    active: dev
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        model: deepseek-r1:7b   # 可更改为其他模型